### ISSUE TITLE
Merge files

### ISSUE THREAD

**Issue by reyesg93** [crabbly/fpdf-laravel#9]
how can merge many pdf and images, to ouput only one pdf?

**Comment by crabbly** [comment]
Hi @reyesg93, the FPDF class is meant to create new PDF files from scratch, not to manipulate existing documents. I recommend looking into pdftk for document manipulation. It's an amazing tool. Here is a link to the pdf labs page with everything you need to know about the program.
https://www.pdflabs.com/

If you prefer compiling it from source code, I have put together a repository to mirror their downloadable source, since they don't provide a git option.
https://github.com/crabbly/pdftk
